name: course_seather_task
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  http: ^0.13.4
  geolocator: ^8.2.0
  toast: ^0.1.5
  shared_preferences: ^2.0.13
  flutter_bloc: ^8.0.1
  provider: ^6.0.2
  weather_icons: ^3.0.0
  flare_flutter: ^3.0.2
  auto_size_text: ^3.0.0
  connectivity: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/animations/